---
- name: create slurm directories
  file: path={{ item }} state=directory owner=root group=root recurse=yes
  with_items:
     - "{{ slurm_config_dir }}"
     - "{{ slurm_pid_dir }}"
  tags:
     - slurm-config

- name: create slurm group
  group: name=slurm state=present
  tags:
     - slurm-config

- name: create slurm user
  user: name=slurm comment="SLURM User" group=slurm generate_ssh_key=yes ssh_key_file=.ssh/id_rsa
  tags:
     - slurm-config

- name: create slurm directories with slurm permissions
  file: path={{ item }} state=directory owner=slurm group=slurm recurse=yes
  with_items:
     - "{{ slurm_log_dir }}"
     - "{{ slurm_spool_dir }}"
  tags:
     - slurm-config

- name: create slurm database
  mysql_db: name={{ slurm_database_name }} state=present
  tags:
     - slurm-config

- name: create slurm database password
  command: /usr/bin/openssl rand -base64 16
  register: mysql_slurm_passwd
  tags:
     - slurm-config

- name: create database user
  mysql_user: name=slurm host={{ item }} password={{ mysql_slurm_passwd.stdout }} priv={{ slurm_database_name}}.*:ALL state=present
  with_items:
     - "{{ inventory_hostname }}"
     - 127.0.0.1
     - ::1
     - localhost
  tags:
     - slurm-config

- name: copy slurm configuration file
  template: src=slurm.conf.j2 dest={{ slurm_config_dir }}/slurm.conf owner=root group=root mode=0644 
  tags:
     - slurm-config
     - slurm-start

- name: copy slurm database configuration file
  template: src=slurmdbd.conf.j2 dest={{ slurm_config_dir }}/slurmdbd.conf owner=root group=root mode=0644
  tags:
     - slurm-config
     - slurm-start

- name: copy slurm init script
  template: src=init.d.slurm.j2 dest=/etc/init.d/slurmd owner=root group=root mode=0755
  tags:
     - slurm-config
     - slurm-start

- name: copy database init script
  template: src=init.d.slurmdbd.j2 dest=/etc/init.d/slurmdbd owner=root group=root mode=0755
  tags:
     - slurm-config

- name: add sbin path
  environment:
     PATH: {{ slurm_dir }}/sbin:{{ ansible_env.PATH }}

- name: add bin path
  environment:
     PATH: {{ slurm_dir }}/bin:{{ ansible_env.PATH }}


- name: add library path
  environment:
     LD_LIBRARY_PATH: {{ slurm_dir }}/lib:{{ ansible_env.LD_LIBRARY_PATH }}


- name: start slurmdbd
  service: name=slurmdbd enabled=yes state=started
  tags:
     - slurm-start
# Initialise the database


- name: start slurmd
  service: name=slurmd enabled=yes state=started
  tags:
     - slurm-start
