---
- name: download slurm source
  get_url: url=http://www.schedmd.com/download/latest/slurm-{{ slurm_version }}.tar.bz2 dest=/tmp
  tags:
     - slurm-download

- name: unarchive slurm
  shell: /bin/tar -xf /tmp/slurm-{{ slurm_version }}.tar.bz2 -C /tmp
  tags:
     - slurm-unarchive

- name: create slurm directory
  file: path={{ slurm_dir }} state=directory owner=root group=root recurse=yes
  tags:
     - slurm-install

- name: run slurm configure
  command: "chdir=/tmp/slurm-{{ slurm_version }} {{ item }}"
  with_items:
      - ./configure --prefix={{ slurm_dir }} --enable-front-end
      - make
      - make install
  tags:
     - slurm-install

- name: create slurm config directory
  file: path={{ slurm_config_dir }} state=directory owner=root group=root recurse=yes
  tags:
     - slurm-config

- name: copy slurm configuration file
  template: src=slurm.conf.j2 dest={{ slurm_config_dir }}/slurm.conf owner=root group=root mode=0644 
  tags:
     - slurm-config

- name: copy slurm database configuration file
  template: src=slurmdbd.conf.j2 dest={{ slurm_config_dir }}/slurmdbd.conf owner=root group=root mode=0644
  tags:
     - slurm-config

- name: copy slurm init script
  template: src=init.d.slurm.j2 dest=/etc/init.d/slurm owner=root group=root mode=0755
  tags:
     - slurm-config

- name: copy database init script
  template: src=init.d.slurmdbd.j2 dest=/etc/init.d/slurmdbd owner=root group=root mode=0755
  tags:
     - slurm-config


