---
- name: create mysql root password
  command: /usr/bin/openssl rand -base64 16
  register: mysql_root_passwd
  tags:
     - mysql_secure_installation
     - mysql
- name: setup root password
  mysql_user: name=root host={{ item }} password={{ mysql_root_passwd.stdout }}
  with_items:
     - "{{ ansible_hostname }}"
     - 127.0.0.1
     - ::1
     - localhost
  tags:
     - mysql_secure_installation
     - mysql


- name: copy my.cnf file
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600
  tags:
     - mysql_secure_installation
     - mysql

- name: delete anonymous mysql user
  mysql_user: name="" state=absent
  tags:
     - mysql_secure_installation
     - mysql

- name: remove mysql test database
  mysql_db: name=test state=absent
  tags:
     - mysql_secure_installation
     - mysql
